Add comparison
insight-platform/SavantPyTorchComparison pull request #1
Opened 2023-11-29 08:36 UTC by abramov-oleg

2023-12-11 08:16 UTC, dorgun requested changes

2023-12-11 08:16 UTC, dorgun commented on .gitignore
> +# ignore everything except labels.txt in a subdirectory
Why did you exclude label.txt? If you need label.txt, you can create it in the onnx export step. In ultralytics, the YOLO class has a names property that returns class names.

2023-12-11 08:16 UTC, dorgun commented on Makefile
> +		-v $(shell pwd)/src/savant:/opt/savant/samples/$(SAVANT_MODULE_NAME) \
```suggestion
		-v `pwd`/src/savant:/opt/savant/samples/$(SAVANT_MODULE_NAME) \
```

2023-12-11 08:16 UTC, dorgun commented on src/pytorch/optimized_pytorch_decode.py
> +        # Crop width
Why is the original frame cropped?

2023-12-11 14:37 UTC, bwsw commented on Makefile
> +		-v $(shell pwd)/src/savant:/opt/savant/samples/$(SAVANT_MODULE_NAME) \
Why not `$(pwd)`?

2023-12-13 06:08 UTC, abramov-oleg commented on Makefile
> +		-v $(shell pwd)/src/savant:/opt/savant/samples/$(SAVANT_MODULE_NAME) \
> Why not `$(pwd)`?

This won't work as this is Makefile, not just shell script. Working alternative would be 

```
$$(pwd)
```

Regarding suggestion, I can change to backticks, no problem, but I don't see anything wrong with the current version.

2023-12-13 07:10 UTC, abramov-oleg commented on Makefile
> +		-v $(shell pwd)/src/savant:/opt/savant/samples/$(SAVANT_MODULE_NAME) \
Changed to backticks.

2023-12-13 07:11 UTC, abramov-oleg commented on .gitignore
> +# ignore everything except labels.txt in a subdirectory
Reworked ONNX export script, removed `labels.txt` from repo.

2024-02-09 10:38 UTC, dorgun approved these changes

2024-02-09 10:59 UTC, merged